### ISSUE TITLE
Shall we replace this one?

### ISSUE THREAD

**Issue by reinzor** [tue-robotics-graveyard/teleop#1]
@jlunenburg 

Is this still active and do we need this? If not, I will move it from this organization to the graveyard.

Why not use http://wiki.ros.org/teleop_twist_keyboard ?

**Comment by Timple** [comment]
The implementation is completely different from the ROS version, since it publishes strings by the looks of it.

However, the issue with the ROS part was that it did not stop upon key release. Maybe we can create a pull request for this.

https://github.com/ros-teleop/teleop_twist_keyboard/issues/8

**Comment by reinzor** [comment]
This sounds good to me!

**Comment by Rayman** [comment]
This package is only needed for key presses (amigo_demo)
